Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2021-06, with the labels that each got.

#54 imlpemented giverrepository
  GiEnJul.Test/GiEnJul.Test.csproj
  GiEnJul/Controllers/PersonController.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Features/GiverReposiory.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Giver.cs
  GiEnJul/Models/Person.cs
Labels: Technical

#56 Added input validators
  GiEnJul/ClientApp/src/components/InputFields/Validators/IValidator.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputPhoneNumber.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/ValidatorFlags.tsx
Labels: Technical

#55 Giver page
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/CollapseContainer.tsx
  GiEnJul/ClientApp/src/components/NavMenu.tsx
  GiEnJul/ClientApp/src/components/Tab.tsx
  GiEnJul/ClientApp/src/routes/Companies.tsx
  GiEnJul/ClientApp/src/routes/How.tsx
  GiEnJul/ClientApp/src/routes/Questions.tsx
  GiEnJul/ClientApp/src/routes/home/Companies.tsx
  GiEnJul/ClientApp/src/routes/home/Home.tsx
  GiEnJul/ClientApp/src/routes/home/How.tsx
  GiEnJul/ClientApp/src/routes/home/Questions.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
Labels: Feature

#58 Added validator packages
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
Labels: bug

#65 Fixed bug when adding persons on registration page
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/RegistrationForm.tsx
Labels: bug

#62 Added adminpage macro component and adminpage project structure
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/admin/common/AdminMenu.tsx
  GiEnJul/ClientApp/src/components/admin/common/style.css
  GiEnJul/ClientApp/src/components/admin/connections/Completed.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Connections.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Suggested.tsx
  GiEnJul/ClientApp/src/routes/Admin.tsx
Labels: Feature

#66 Refactorinstitutionpage and fixed warnings
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/NavMenu.tsx
  GiEnJul/ClientApp/src/components/Registration.tsx
  GiEnJul/ClientApp/src/components/Tab.tsx
  GiEnJul/ClientApp/src/components/admin/common/AdminMenu.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Connections.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionLocation.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionMacro.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionPerson.tsx
  GiEnJul/ClientApp/src/routes/home/Home.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
Labels: Technical

#69 Added some logging to GenericRepository-functions. Resolves #52
  GiEnJul/Features/GenericRepository.cs
  GiEnJul/Features/PersonRepository.cs
Labels: Technical

#70 Fixed build error after faulty PR
  GiEnJul/Features/GiverReposiory.cs
Labels: Technical

#74 Added ci workflows
  .github/workflows/main_backend.yml
  .github/workflows/main_frontend.yml
Labels: Technical

#73 Connection with table storage
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/routes/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Models/Giver.cs
  GiEnJul/Startup.cs
Labels: Technical

#80 Add Actions to Readme.md
  README.md
Labels: Feature

#84 Added recipient repository
  GiEnJul/Features/GenericRepository.cs
  GiEnJul/Features/RecipientRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
Labels: Technical

#87 Implemented Connectionrepository
  GiEnJul/Entities/Connection.cs
  GiEnJul/Features/ConnectionRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Recipient.cs
Labels: Technical

#88 Updated Table Storage diagram
  assets/ERDiagram_old.png
  assets/TableStorageDiagram.png
Labels: Technical

#90 Fixed the recipient mappings
  GiEnJul/Entities/Recipient.cs
Labels: bug

#91 Added common location variable
  GiEnJul/ClientApp/src/common/constants/Locations.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
Labels: Technical

#92 Implement marterial UI
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/public/index.html
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/CollapseContainer.tsx
  GiEnJul/ClientApp/src/components/Counter.tsx
  GiEnJul/ClientApp/src/components/FetchData.tsx
  GiEnJul/ClientApp/src/components/NavMenu.tsx
  GiEnJul/ClientApp/src/routes/home/Companies.tsx
  GiEnJul/ClientApp/src/routes/home/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/home/Home.tsx
  GiEnJul/ClientApp/src/routes/home/How.tsx
  GiEnJul/ClientApp/src/routes/home/Questions.tsx
  GiEnJul/ClientApp/src/routes/home/Styles.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
  GiEnJul/package-lock.json
Labels: Feature

#94 implemented Institutions POST
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
Labels: Feature

#99 Changed assertions to reflect input to annet field
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
Labels: bug

#98 Change Test-framework to xunit, and testing GiverController
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul.Test/GiEnJul.Test.csproj
  GiEnJul.Test/ModelTests/GiverTest.cs
  GiEnJul.Test/ModelTests/ModelValidator.cs
  GiEnJul.Test/UnitTest1.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Features/ConnectionRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Giver.cs
Labels: Technical, question

#100 Default error handling
  GiEnJul/Controllers/ErrorController.cs
  GiEnJul/Startup.cs
Labels: Technical

#111 Fixed the recipient url typo
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
Labels: bug

#108 Change autofocus to start at full name in Giver-registration
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
Labels: Feature

#112 Log when Repository is unable to connect to Table
  GiEnJul/Features/GenericRepository.cs
Labels: Technical

#95 Recipient controller
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Features/GenericRepository.cs
  GiEnJul/Features/PersonRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Person.cs
  GiEnJul/Models/Recipient.cs
  package-lock.json
Labels: Technical

#116 added try catch for signup process
  GiEnJul/ClientApp/src/routes/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
Labels: Feature

#123 Validation givers
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/routes/home/How.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
Labels: Feature

#122 added automapperTest and fixed profile
  GiEnJul.Test/InfrastructureTests/AutoMapperTest.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Person.cs
Labels: Feature, Technical

#132 GenericRepository GetAllAsync and GetAllByQueryAsync
  GiEnJul/Entities/Connection.cs
  GiEnJul/Entities/EntityBase.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Entities/Person.cs
  GiEnJul/Entities/Recipient.cs
  GiEnJul/Features/GenericRepository.cs
Labels: Technical

#129 Added tests for recipient controller
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul.Test/ModelTests/RecipientTest.cs
  GiEnJul/Entities/Recipient.cs
  GiEnJul/Models/Recipient.cs
Labels: Technical

#137 Connectionscomponent
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/common/Circle.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Completed.tsx
  GiEnJul/ClientApp/src/components/admin/connections/ConnectionStyles.tsx
  GiEnJul/ClientApp/src/components/admin/connections/ConnectionsField.tsx
Labels: Feature
