Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2021-08, with the labels that each got.

#317 Fetch recipients with location from user
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Technical

#318 Frontend - simple footer and Stepper for progress on registration
  GiEnJul/ClientApp/src/common/components/Footer.tsx
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/components/landingPage/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Pager.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: Feature

#323 Typo bug
  GiEnJul/Controllers/AdminController.cs
Labels: bug

#324 GitHub workflows rename
  .github/workflows/CD_backend.yml
  .github/workflows/CD_frontend.yml
  .github/workflows/CI_backend.yml
  .github/workflows/CI_frontend.yml
Labels: Technical

#322 Activate backend auth
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/completed/DeliveryExcelDownload.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionMacro.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/RecipientController.cs
Labels: Technical

#321 fixed the problem with no errorhandling on confirmation page
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: bug

#326 User experience and improved performance in overviewAdmin
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/RecipientTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/Styles.tsx
  GiEnJul/ClientApp/src/components/admin/overview/ConnectButton.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Giver.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Recipient.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Styles.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Types.tsx
  GiEnJul/ClientApp/src/index.tsx
Labels: Feature, Technical

#325 Institution info
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
Labels: Feature

#319 Recaptcha
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul.Test/ModelTests/GiverTest.cs
  GiEnJul/ClientApp/.env
  GiEnJul/ClientApp/.env.production
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/admin/completed/DeliveryExcelDownload.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/index.tsx
  GiEnJul/ClientApp/tsconfig.json
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Dtos/GetRecaptchaDto.cs
  GiEnJul/Dtos/PostGiverDto.cs
  GiEnJul/Helpers/ConnectionHelper.cs
  GiEnJul/Helpers/TableQueryFilterHelper.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Infrastructure/Settings.cs
  GiEnJul/Utilities/RecaptchaVerifier.cs
  GiEnJul/appsettings.json
Labels: Feature

#333 Update CD_frontend.yml
  .github/workflows/CD_frontend.yml
Labels: bug

#332 Capitalized gi en jul when it refere to the brand. Lowercased if not.
  GiEnJul/ClientApp/src/components/landingPage/Companies.tsx
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Questions.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
Labels: invalid

#328 Padding to institutionPage
  GiEnJul/ClientApp/src/components/institution/InstitutionMacro.tsx
  GiEnJul/ClientApp/src/components/institution/Styles.tsx
Labels: Feature

#334 Fix verify controller
  GiEnJul/Controllers/VerifyConnectionController.cs
Labels: bug

#336 Fixed bug for transparent header
  GiEnJul/ClientApp/src/common/components/Styles.tsx
Labels: bug

#342 Update CD_frontend.yml
  .github/workflows/CD_frontend.yml
Labels: bug

#338 Removed testing code. Removed badge and added a text in summary instead.
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/custom.css
  GiEnJul/ClientApp/src/index.tsx
Labels: Feature

#339 Fixed bug when no locations is fetched
  GiEnJul/ClientApp/src/common/constants/Locations.tsx
Labels: bug

#340 bug adminNav
  GiEnJul/ClientApp/src/common/components/NavMenuAdmin.tsx
  GiEnJul/ClientApp/src/components/login/LogOutButton.tsx
Labels: bug

#343 Fixed transparent header bug
  GiEnJul/ClientApp/src/common/components/Styles.tsx
Labels: bug

#351 Commented in code in the recaptcha utility, so it is disabled on dev
  GiEnJul/Utilities/RecaptchaVerifier.cs
Labels: Technical

#349 Add illustrations by Stine
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Macro.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/styling/img/Arrow down.svg
  GiEnJul/ClientApp/src/styling/img/familyTop.svg
  GiEnJul/ClientApp/src/styling/img/logo_background.svg
  GiEnJul/ClientApp/src/styling/img/snow_down.svg
  GiEnJul/ClientApp/src/styling/img/snow_up.svg
  GiEnJul/ClientApp/src/styling/img/snow_up2.svg
Labels: extra

#352 changed map field
  GiEnJul/Infrastructure/AutoMapperProfile.cs
Labels: bug

#344 Frontend - statistics
  GiEnJul/ClientApp/src/components/admin/overview/ConnectButton.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Statistics.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Styles.tsx
Labels: Feature

#354 Backendfetchconnections
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/GetConnectionDto.cs
  GiEnJul/Helpers/TableQueryFilterHelper.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Repositories/ConnectionRepository.cs
  GiEnJul/Repositories/GiverRepository.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Technical

#360 Design on confirmationGiver and verifyConnection
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/verifyConnection/verifyConnection.tsx
  GiEnJul/ClientApp/src/styling/img/Group 1065.svg
  GiEnJul/ClientApp/src/styling/img/Group 740 (1).svg
  GiEnJul/ClientApp/src/styling/img/Group 741 (1).svg
  GiEnJul/ClientApp/src/styling/img/snow_down2.svg
  GiEnJul/ClientApp/src/styling/img/snowman.svg
  GiEnJul/ClientApp/src/styling/img/snowmanFull.svg
Labels: Feature

#358 Recaptcha text
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: Feature

#361 text and styling
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/components/verifyConnection/verifyConnection.tsx
  GiEnJul/ClientApp/src/styling/img/DoubleArrowup.svg
Labels: Feature

#368 Bug negative numbers in OverviewStatistics
  GiEnJul/ClientApp/src/components/admin/overview/Statistics.tsx
Labels: bug

#369 README startup guide
  README.md
Labels: Feature

#366 Frontend - Added privacy checkbox and dialog in giver registration summary
  GiEnJul/ClientApp/src/components/registerGiver/PrivacyDialog.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: Feature

#373 Added loading screen to giver registration for when location is not f…
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
Labels: Technical

#387 Landing page styling
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/verifyConnection/verifyConnection.tsx
  GiEnJul/ClientApp/src/index.tsx
  GiEnJul/ClientApp/src/styling/img/step1.svg
  GiEnJul/ClientApp/src/styling/img/step2.svg
  GiEnJul/ClientApp/src/styling/img/step3.svg
Labels: Feature

#394 Padding fixes
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: bug

#391 Changed giver registration email
  GiEnJul/Controllers/GiverController.cs
Labels: Technical
