Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2021-07, with the labels that each got.

#138 Delete package-lock.json
  package-lock.json
Labels: bug, invalid

#139 Changed how InputValidation is implemented. Added material ui to Inpu…
  .gitignore
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/components/InputFields/Validators/IValidator.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputEmail.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputNotNull.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputPhoneNumber.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/ValidatorFlags.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/Validators.tsx
  GiEnJul/ClientApp/src/components/institution/FormPerson.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
  GiEnJul/package-lock.json
Labels: Technical

#144 Changed Giver-submission field
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
Labels: Technical

#148 Continuous deployment
  .github/workflows/deploy.yml
Labels: Technical

#149 Update deploy.yml
  .github/workflows/deploy.yml
Labels: bug

#141 Change giver fields
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/StylesTab.tsx
  GiEnJul/ClientApp/src/components/Tab.css
  GiEnJul/ClientApp/src/components/Tab.tsx
  GiEnJul/ClientApp/src/routes/home/Home.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/routes/registerGiver/SummaryRegistration.tsx
Labels: Feature

#151 Fixed warning appearing in console
  GiEnJul/ClientApp/src/components/Layout.tsx
  GiEnJul/ClientApp/src/components/nav/NavMenu.css
  GiEnJul/ClientApp/src/components/nav/NavMenu.tsx
Labels: bug

#142 Added Events, and refactored Giver to support events
  GiEnJul.Test/ControllerTests/BaseControllerTest.cs
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul.Test/ModelTests/GiverTest.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Dtos/PostGiverDto.cs
  GiEnJul/Entities/Event.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Features/EventRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Giver.cs
Labels: Technical

#154 Admin edit landing page
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/common/components/NavMenu.css
  GiEnJul/ClientApp/src/common/components/NavMenu.tsx
  GiEnJul/ClientApp/src/common/components/NavMenuAdmin.tsx
  GiEnJul/ClientApp/src/common/components/StylesTab.tsx
  GiEnJul/ClientApp/src/common/components/Tab.tsx
  GiEnJul/ClientApp/src/components/Layout.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/editLandingPage/EditMacro.tsx
  GiEnJul/ClientApp/src/components/admin/editLandingPage/EditQuestions.tsx
  GiEnJul/ClientApp/src/components/home/Companies.tsx
  GiEnJul/ClientApp/src/components/home/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/home/Home.tsx
  GiEnJul/ClientApp/src/components/home/How.tsx
  GiEnJul/ClientApp/src/components/home/Questions.tsx
  GiEnJul/ClientApp/src/components/home/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SummaryRegistration.tsx
  GiEnJul/ClientApp/src/routes/Admin.tsx
Labels: Feature

#155 Added confirmation to institution form
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
Labels: Feature

#156 Update deploy.yml
  .github/workflows/deploy.yml
Labels: bug, invalid

#157 Ran code cleanup on solution
  GiEnJul/Controllers/ErrorController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Entities/Connection.cs
  GiEnJul/Entities/Event.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Entities/Person.cs
  GiEnJul/Entities/Recipient.cs
  GiEnJul/Features/ConnectionRepository.cs
  GiEnJul/Features/GenericRepository.cs
  GiEnJul/Features/GiverReposiory.cs
  GiEnJul/Features/PersonRepository.cs
  GiEnJul/Features/RecipientRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Person.cs
  GiEnJul/Models/Recipient.cs
  GiEnJul/package-lock.json
Labels: extra

#159 Added material ui to locations, persons, dinner and dessert forms in …
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/common/constants/Desserts.tsx
  GiEnJul/ClientApp/src/common/constants/Dinners.tsx
  GiEnJul/ClientApp/src/common/constants/Genders.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/institution/FormFood.tsx
  GiEnJul/ClientApp/src/components/institution/FormPerson.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionInfo.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionLocation.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionLocations.tsx
Labels: Feature

#164 Added function to retrieve active locations based of the events table
  GiEnJul.Test/ControllerTests/EventControllerTest.cs
  GiEnJul/Controllers/EventController.cs
  GiEnJul/Features/EventRepository.cs
Labels: Technical

#165 Auth0 implementation
  GiEnJul/ClientApp/.env
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/common/components/LoadingPage.tsx
  GiEnJul/ClientApp/src/common/constants/DotLoader.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/home/Home.tsx
  GiEnJul/ClientApp/src/components/login/LogOutButton.tsx
  GiEnJul/ClientApp/src/components/login/LoginButton.tsx
  GiEnJul/ClientApp/src/components/login/LoginPage.tsx
  GiEnJul/ClientApp/src/index.tsx
Labels: Feature

#173 Changed return types for GiverController and GiverRepository
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Dtos/PostGiverResultDto.cs
  GiEnJul/Features/GiverReposiory.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
Labels: Technical

#174 Added properties to the entities Giver and Recipient
  GiEnJul/Entities/Giver.cs
  GiEnJul/Entities/Recipient.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Giver.cs
  GiEnJul/Models/Recipient.cs
Labels: Technical

#176 Changed logoutbutton
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/login/LogOutButton.tsx
Labels: bug

#178 Change return types for RecipientController and RecipientRepository
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Features/RecipientRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
Labels: Technical

#182 jesttypes newest edition fixed it
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
Labels: bug

#185 Fix package.json
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/home/ContactInfo.tsx
  GiEnJul/ClientApp/tsconfig.json
Labels: bug

#186 Roleretrival
  GiEnJul/ClientApp/src/common/constants/DotLoader.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/common/AdminMenu.tsx
  GiEnJul/ClientApp/src/components/common/ErrorPage.tsx
  GiEnJul/ClientApp/src/index.tsx
Labels: Feature

#189 Replaced static LOCATIONS with function GetLocations
  GiEnJul/ClientApp/src/common/constants/Locations.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionLocations.tsx
  GiEnJul/ClientApp/src/components/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SummaryRegistration.tsx
  GiEnJul/Features/EventRepository.cs
Labels: Feature

#179 Added alert component. Added alert component to institution form
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
Labels: Feature

#190 Admincontroller & datatable of givers
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/common/Datatable.tsx
  GiEnJul/ClientApp/src/components/admin/common/Styles.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Giver.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Features/RecipientRepository.cs
Labels: Feature, Technical

#199 Changed the access modifiers of GenericRepository, and removed the GenericRepo interface
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Features/ConnectionRepository.cs
  GiEnJul/Features/EventRepository.cs
  GiEnJul/Features/GenericRepository.cs
  GiEnJul/Features/GiverRepository.cs
  GiEnJul/Features/PersonRepository.cs
  GiEnJul/Features/RecipientRepository.cs
Labels: Technical, extra

#204 UseFetch
  GiEnJul/ClientApp/src/components/admin/editLandingPage/EditMacro.tsx
  GiEnJul/ClientApp/src/components/home/Home.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/hooks/useFetch.tsx
  GiEnJul/ClientApp/src/index.tsx
Labels: Technical

#206 fix my error
  GiEnJul/ClientApp/src/index.tsx
Labels: bug

#207 Usepost
  GiEnJul/ClientApp/src/hooks/usePost.tsx
Labels: Technical

#200 Cleaned up giver registration. Collected all giver states into bigger…
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/common/constants/FamilySizes.tsx
  GiEnJul/ClientApp/src/components/InputFields/SelectForm.tsx
  GiEnJul/ClientApp/src/components/InputFields/SelectInput.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/home/Home.tsx
  GiEnJul/ClientApp/src/components/institution/FormFood.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/IFormData.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
  GiEnJul/ClientApp/src/components/registerGiver/LocationGiver.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Pager.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SignUp.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/components/registerGiver/SummaryRegistration.tsx
Labels: Technical

#226 Put institution states into a state object
  GiEnJul/ClientApp/src/components/institution/FormFood.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
Labels: Technical

#227 Add files via upload
  assets/logo_small.png
Labels: extra

#225 Post connection in admin controller
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Entities/Connection.cs
  GiEnJul/Exceptions/InvalidEventException.cs
  GiEnJul/Features/ConnectionRepository.cs
  GiEnJul/Features/GiverRepository.cs
  GiEnJul/Features/RecipientRepository.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
Labels: Technical

#229 Put states into object states
  GiEnJul/ClientApp/src/components/institution/FormPerson.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
Labels: Technical

#236 Added script that creates tables with recipients, givers and persons
  .gitignore
  scripts/filldb/README.md
  scripts/filldb/data/lastnames.txt
  scripts/filldb/data/names_female.txt
  scripts/filldb/data/names_male.txt
  scripts/filldb/data/wishes.txt
  scripts/filldb/data/words.txt
  scripts/filldb/filldb.py
Labels: Technical

#237 Fix receiver typo
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul.Test/ModelTests/GiverTest.cs
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Giver.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/Dtos/PostGiverDto.cs
  GiEnJul/Entities/Connection.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Models/Giver.cs
Labels: invalid

#234 Implemented EmailClient with "dummy" sender-email. Givers now receive an confirmation on registering
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul/Clients/EmailClient.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Dtos/PostGiverResultDto.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Infrastructure/Settings.cs
  GiEnJul/appsettings.json
Labels: Feature, Technical

#246 Fixed warnings on admin/overview
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/RecipientTable.tsx
Labels: bug

#244 Added key attribute to nav buttons. Ran prettier on EditMacro.tsx
  GiEnJul/ClientApp/src/components/admin/editLandingPage/EditMacro.tsx
Labels: bug

#248 Fixed filldb path bug
  scripts/filldb/filldb.py
Labels: bug

#243 Scroll event listener is now removed on unmounting
  GiEnJul/ClientApp/src/common/components/Tab.tsx
Labels: bug

#232 Consistent return in repository
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Features/ConnectionRepository.cs
Labels: Technical

#233 Backendatuh0implement
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/Auth/HasScopeHandler.cs
  GiEnJul/Auth/HasScopeRequirement.cs
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/index.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Infrastructure/Settings.cs
  GiEnJul/Startup.cs
  GiEnJul/appsettings.json
Labels: Technical

#259 Added controller to verify creation of a connection
  GiEnJul/Controllers/VerifyConnectionController.cs
  GiEnJul/Exceptions/InvalidConnectionCreationException.cs
  GiEnJul/Helpers/ConnectionHelper.cs
Labels: Technical

#261 Fixed maxReceivers typo in filldb.py. Added InternalId to giver table
  scripts/filldb/filldb.py
Labels: Technical, bug

#264 Deletegiverfunc
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/DeleteGiverDto.cs
Labels: Technical

#265 Added component for givers that verify their assigned connection
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/components/verifyConnection/verifyConnection.tsx
  GiEnJul/Helpers/ConnectionHelper.cs
Labels: Feature

#266 Deletereceiverfunc
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/DeleteRecipientDto.cs
Labels: Technical

#250 Task231 frontend connections
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/RecipientTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/Styles.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Giver.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Recipient.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Types.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/PostConnectionDto.cs
Labels: Feature

#269 Fixed fetched events to be filtered by StartDate and EndDate.
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul/Entities/Event.cs
  GiEnJul/Features/EventRepository.cs
Labels: Technical, extra

#271 removed dup import and renamed .tsx to .ts
  GiEnJul/ClientApp/src/components/admin/overview/Types.ts
  GiEnJul/Controllers/AdminController.cs
Labels: invalid

#272 SuggestConnectionAsync now sends an email to givers
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Infrastructure/Settings.cs
  GiEnJul/appsettings.json
Labels: Feature, Technical

#273 Renamed features to repositories
  GiEnJul.Test/ControllerTests/EventControllerTest.cs
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/EventController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Controllers/VerifyConnectionController.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Repositories/ConnectionRepository.cs
  GiEnJul/Repositories/EventRepository.cs
  GiEnJul/Repositories/GenericRepository.cs
  GiEnJul/Repositories/GiverRepository.cs
  GiEnJul/Repositories/PersonRepository.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: extra

#276 Fixed error with email-body
  GiEnJul/Controllers/AdminController.cs
Labels: bug

#260 Added autoincrement table. Added readable id to recipient.
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Entities/AutoIncrement.cs
  GiEnJul/Entities/Recipient.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Recipient.cs
  GiEnJul/Repositories/AutoIncrementRepository.cs
  GiEnJul/Repositories/GenericRepository.cs
  scripts/filldb/filldb.py
Labels: Technical

#278 Fixed bugs on institution registration page
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/institution/FormFood.tsx
  GiEnJul/ClientApp/src/components/institution/FormPerson.tsx
  GiEnJul/ClientApp/src/components/institution/IFormPerson.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionLocations.tsx
Labels: bug

#280 Removed unnessesary call to Person-table in SuggestConnection-function.
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Technical

#282 added gienjul favicon and changed the title
  GiEnJul/ClientApp/public/favicon.ico
  GiEnJul/ClientApp/public/index.html
  GiEnJul/ClientApp/public/manifest.json
Labels: Feature

#289 Added endpoint to fetch random set of Givers that are unmatched
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/GiverDataTableDto.cs
  GiEnJul/Helpers/SuggestionHelper.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Recipient.cs
  GiEnJul/Repositories/GiverRepository.cs
Labels: Technical

#291 Remove unused method after PersonCount was added to Models.Recipient
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Technical

#292 implemented apiservice in admin overviewMacro
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
Labels: Technical

#293 Added api-function for fetching a random set of Recipient based of location and event
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/RecipientDataTableDto.cs
  GiEnJul/Helpers/TableQueryFilterHelper.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Repositories/GiverRepository.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Technical

#295 Selectform bug
  GiEnJul/ClientApp/src/components/InputFields/SelectForm.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
Labels: bug

#288 Added generation of delivery excel. Added familyid to connection
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Entities/Connection.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Repositories/ConnectionRepository.cs
  GiEnJul/Utilities/ExcelEntries/DeliveryExcel.cs
  GiEnJul/Utilities/ExcelEntries/IExcel.cs
  GiEnJul/Utilities/ExcelGenerator.cs
Labels: Feature

#298 Frontend delivery excel
  GiEnJul/ClientApp/src/common/functions/apiServiceClass.ts
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/completed/ConnectionStyles.tsx
  GiEnJul/ClientApp/src/components/admin/completed/ConnectionsField.tsx
  GiEnJul/ClientApp/src/components/admin/completed/DeliveryExcelDownload.tsx
  GiEnJul/ClientApp/src/components/admin/completed/Macro.tsx
  GiEnJul/ClientApp/src/components/admin/completed/Table.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Connections.tsx
  GiEnJul/ClientApp/src/components/admin/connections/Suggested.tsx
Labels: Feature

#302 Fetchtoapiservice
  GiEnJul/ClientApp/src/common/constants/Locations.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionForm.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/components/verifyConnection/verifyConnection.tsx
Labels: Technical

#296 Design and styling on LandingPage and RegisterGiver
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/App.tsx
  GiEnJul/ClientApp/src/common/components/NavBar.tsx
  GiEnJul/ClientApp/src/common/components/NavMenu.tsx
  GiEnJul/ClientApp/src/common/components/NavMenuAdmin.css
  GiEnJul/ClientApp/src/common/components/NavMenuAdmin.tsx
  GiEnJul/ClientApp/src/common/components/ScrollToTop.tsx
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/common/components/StylesTab.tsx
  GiEnJul/ClientApp/src/common/components/Tab.tsx
  GiEnJul/ClientApp/src/components/InputFields/SelectForm.tsx
  GiEnJul/ClientApp/src/components/InputFields/Validators/InputValidator.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/RecipientTable.tsx
  GiEnJul/ClientApp/src/components/admin/editLandingPage/EditMacro.tsx
  GiEnJul/ClientApp/src/components/home/Home.tsx
  GiEnJul/ClientApp/src/components/home/How.tsx
  GiEnJul/ClientApp/src/components/home/Questions.tsx
  GiEnJul/ClientApp/src/components/home/Styles.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionMacro.tsx
  GiEnJul/ClientApp/src/components/landingPage/Companies.tsx
  GiEnJul/ClientApp/src/components/landingPage/Contact.tsx
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Macro.tsx
  GiEnJul/ClientApp/src/components/landingPage/Questions.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Confirmation.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Macro.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Pager.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/custom.css
  GiEnJul/ClientApp/src/index.tsx
  GiEnJul/ClientApp/src/styling/img/logo_black.svg
  GiEnJul/ClientApp/src/styling/img/logo_green.png
  GiEnJul/ClientApp/src/styling/img/logo_green.svg
Labels: Feature

#304 Added location and auth to delivery excel download. Added useUser hook.
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/completed/DeliveryExcelDownload.tsx
  GiEnJul/ClientApp/src/components/admin/completed/Macro.tsx
  GiEnJul/ClientApp/src/hooks/useUser.tsx
  GiEnJul/Controllers/AdminController.cs
Labels: Feature

#303 Fixed bug on Admin - Overview
  GiEnJul/ClientApp/src/components/admin/common/GiverTable.tsx
  GiEnJul/ClientApp/src/components/admin/common/RecipientTable.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Giver.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Recipient.tsx
  GiEnJul/ClientApp/src/components/admin/overview/Types.ts
Labels: Feature

#305 Refactoredadminpage
  GiEnJul/ClientApp/src/common/components/NavMenuAdmin.tsx
  GiEnJul/ClientApp/src/components/admin/AdminPage.tsx
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/completed/Macro.tsx
  GiEnJul/ClientApp/src/components/institution/InstitutionMacro.tsx
  GiEnJul/ClientApp/src/hooks/useUser.tsx
Labels: Feature

#307 Mobile/desktopview on landingPage-how component
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/package.json
  GiEnJul/ClientApp/src/App.test.tsx
  GiEnJul/ClientApp/src/common/components/ScrollToTop.tsx
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/index.tsx
  GiEnJul/ClientApp/src/styling/img/dummy-image.jpg
Labels: Feature

#309 Styling landing and registration page
  GiEnJul/ClientApp/package-lock.json
  GiEnJul/ClientApp/src/common/components/NavBar.tsx
  GiEnJul/ClientApp/src/common/components/Styles.tsx
  GiEnJul/ClientApp/src/components/landingPage/Companies.tsx
  GiEnJul/ClientApp/src/components/landingPage/Contact.tsx
  GiEnJul/ClientApp/src/components/landingPage/How.tsx
  GiEnJul/ClientApp/src/components/landingPage/Questions.tsx
  GiEnJul/ClientApp/src/components/landingPage/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/ContactInfo.tsx
  GiEnJul/ClientApp/src/components/registerGiver/FamilySize.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Location.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Styles.tsx
  GiEnJul/ClientApp/src/components/registerGiver/Summary.tsx
  GiEnJul/ClientApp/src/index.tsx
Labels: Feature

#315 Fetch givers with location from auth0-user
  GiEnJul/ClientApp/src/components/admin/AdminTab.tsx
  GiEnJul/ClientApp/src/components/admin/overview/OverviewMacro.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Helpers/TableQueryFilterHelper.cs
  GiEnJul/Repositories/GiverRepository.cs
Labels: Technical
