Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2021-09, with the labels that each got.

#409 Dynamiccontactlist/398
  ClientApp/src/components/landingPage/Contact.tsx
  ClientApp/src/components/landingPage/Macro.tsx
  GiEnJul/Controllers/EventController.cs
  GiEnJul/Dtos/GetContactsDto.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Repositories/EventRepository.cs
Labels: Feature, Priority Medium

#420 Fix410/change id placeholder fixes #410
  ClientApp/src/components/institution/InstitutionForm.tsx
Labels: Feature

#416 Suggest givers based on registration date
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Dtos/GiverDataTableDto.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Helpers/SuggestionHelper.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Event.cs
  GiEnJul/Models/Giver.cs
  GiEnJul/Repositories/GiverRepository.cs
Labels: Feature, Technical

#421 Fixed mapping to read "RowKey" as "City" instead
  ClientApp/src/components/landingPage/Contact.tsx
  GiEnJul/Infrastructure/AutoMapperProfile.cs
Labels: bug, Priority Medium

#426 Added "Image" readable from database
  ClientApp/src/components/landingPage/Contact.tsx
  GiEnJul/Dtos/GetContactsDto.cs
  GiEnJul/Dtos/PostEventDto.cs
  GiEnJul/Entities/Event.cs
  GiEnJul/Models/Event.cs
Labels: Feature
