Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2022-07, with the labels that each got.

#685 Family information supplied on connection
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Models/Person.cs
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
Labels: Backend

#688 Added component to recipienttable and minor fix
  ClientApp/src/components/admin/dashboard-all/GiverTable.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientTable.tsx
  ClientApp/src/components/shared/SendEmailContent.tsx
Labels: Frontend

#698 superAdmin Mange Page made
  ClientApp/src/components/superadmin/Styles.tsx
  ClientApp/src/components/superadmin/manage-dashboard/ManageDashboard.tsx
  ClientApp/src/pages/administrator/index.tsx
  ClientApp/src/pages/login/index.tsx
Labels: Frontend

#696 Giver disconnect from email
  ClientApp/src/App.tsx
  ClientApp/src/pages/DenyConnection.tsx
  ClientApp/src/pages/VerifyConnection.tsx
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Dtos/PostFeedbackGiverDto.cs
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
Labels: Backend, Frontend

#704 Hover Notification
  ClientApp/src/components/institution/CustomTooltip.tsx
  ClientApp/src/components/institution/InstitutionForm.tsx
  ClientApp/src/components/institution/Styles.tsx
Labels: Frontend

#707 Suggestion hover
  ClientApp/src/components/institution/InstitutionInfo.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/components/institution/SuggestionPopover.tsx
Labels: Frontend

#716 Backend for superadmin manage page
  GiEnJul/Controllers/SuperAdminController.cs
  GiEnJul/Dtos/PostCmsDto.cs
  GiEnJul/Entities/Cms.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Models/Cms.cs
  GiEnJul/Repositories/CmsRepository.cs
Labels: Backend

#717 changed name of controller
  GiEnJul/Controllers/CmsController.cs
Labels: Backend

#720 Fix email templates
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Utilities/EmailTemplates/EmailTemplateBuilder.cs
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily.html
  GiEnJul/Utilities/EmailTemplates/Files/Notification.html
  GiEnJul/Utilities/EmailTemplates/Files/Registered.html
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
  GiEnJul/Utilities/EmailTemplates/Files/WaitingList.html
  GiEnJul/Utilities/EmailTemplates/Files/familyTop.png
Labels: Backend

#722 email templates get info from json
  GiEnJul/GiEnJul.csproj
  GiEnJul/Utilities/EmailTemplates/EmailTemplateBuilder.cs
  GiEnJul/Utilities/EmailTemplates/Files/EmailCssStyles.json
  GiEnJul/Utilities/EmailTemplates/Files/TemplateStyle.css
  GiEnJul/Utilities/EmailTemplates/Files/familyTop.0ff49710.svg
Labels: Backend

#721 editBusninessPageText
  ClientApp/package.json
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  GiEnJul/Controllers/CmsController.cs
Labels: Backend, Frontend

#729 Design changes
  ClientApp/src/components/register-as-giver/Confirmation.tsx
  ClientApp/src/components/register-as-giver/ContactInfo.tsx
  ClientApp/src/components/register-as-giver/FamilySize.tsx
  ClientApp/src/components/register-as-giver/Location.tsx
  ClientApp/src/components/register-as-giver/Pager.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/components/register-as-giver/Summary.tsx
  ClientApp/src/components/shared/input-fields/validators/InputValidator.tsx
  ClientApp/src/index.tsx
  ClientApp/src/pages/register-as-giver/index.tsx
  ClientApp/src/styling/img/bli_giver.png
Labels: Frontend

#732 Bug business page
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  GiEnJul/Controllers/CmsController.cs
  GiEnJul/Repositories/CmsRepository.cs
Labels: Backend, Frontend

#733 added button to editing business manage page
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/confirmationBox.tsx
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  ClientApp/src/components/superadmin/Styles.tsx
Labels: Frontend

#758 fixed unneccecerily request
  ClientApp/src/components/superadmin/kommune/KommuneInformation.tsx
  ClientApp/src/pages/municipality/index.tsx
Labels: bug

#762 Delete entry
  ClientApp/package-lock.json
  ClientApp/src/components/superadmin/kommune/KommuneInformation.tsx
  GiEnJul/Controllers/CmsController.cs
  GiEnJul/Repositories/CmsRepository.cs
Labels: Backend, Frontend

#769 Add entry
  GiEnJul/Controllers/EventController.cs
Labels: Backend

#764 Faq cms manage
  ClientApp/src/components/landing-page/Questions.tsx
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  ClientApp/src/components/superadmin/Faq/FaqContainer.tsx
  ClientApp/src/components/superadmin/Faq/FaqInformation.tsx
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  ClientApp/src/components/superadmin/Styles.tsx
Labels: Frontend

#776 family info component finished
  ClientApp/src/components/institution/NewDesign/FamilyInformationBox.tsx
  ClientApp/src/components/institution/NewDesign/RegistrationFormRemake.tsx
  ClientApp/src/components/institution/Styles.tsx
Labels: Frontend

#778 Allow admin to edit
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  ClientApp/src/components/superadmin/kommune/KommuneContainer.tsx
  ClientApp/src/components/superadmin/kommune/KommuneInformation.tsx
  ClientApp/src/pages/administrator/index.tsx
  ClientApp/src/pages/login/index.tsx
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/Controllers/CmsController.cs
Labels: Backend, Frontend

#784 Use feedback
  ClientApp/src/components/admin/dashboard-all/GiverTable.tsx
  ClientApp/src/components/shared/Types.tsx
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Entities/Giver.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Giver.cs
Labels: Backend, Frontend

#794 Admin overview filtration
  ClientApp/src/common/constants/ConnectionColors.tsx
  ClientApp/src/components/admin/dashboard-all/GiverSearch.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientSearch.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientTable.tsx
Labels: Frontend

#800 added how to start page
  ClientApp/src/components/landing-page/StartJul.tsx
  ClientApp/src/components/superadmin/InfoPages/HowToStartGiEnJul.tsx
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  GiEnJul/Controllers/CmsController.cs
Labels: Frontend

#808 Registration form stepper
  ClientApp/src/components/register-as-giver/Steppers.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/index.tsx
  ClientApp/src/pages/register-as-giver/index.tsx
Labels: Design

#816 add endpoint for creating excel table
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Infrastructure/AutoMapperConfiguration.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Infrastructure/ExcelProfile.cs
  GiEnJul/Utilities/ExcelEntries/SubmittedFamiliesExcel.cs
  GiEnJul/Utilities/ExcelEntries/SubmittedPersonExcel.cs
  GiEnJul/Utilities/ExcelGenerator.cs
Labels: Backend

#818 Add scheduled job functionality
  GiEnJul/GiEnJul.csproj
  GiEnJul/Startup.cs
  GiEnJul/Utilities/ScheduledJobs/CleanupConnectionsJob.cs
  GiEnJul/Utilities/ServiceCollectionQuartzConfiguratorExtensions.cs
  GiEnJul/appsettings.json
Labels: Backend

#781 Navbar landing page
  ClientApp/src/common/functions/IsMobile.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
Labels: Frontend

#827 NAvbar fix beutiful
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarBusiness.tsx
  ClientApp/src/components/shared/navbar/NavBarMobile.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
  ClientApp/src/pages/municipality/index.tsx
  ClientApp/src/styling/img/logo_white.svg
Labels: Frontend

#828 Continue on admin oversikt
  ClientApp/package.json
  ClientApp/src/common/constants/ConnectionColors.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewStatistics.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/ScrollerComponent.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
  ClientApp/src/components/institution/Old/oldInstForm.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/pages/administrator/index.tsx
Labels: Frontend

#829 Institution form
  ClientApp/src/components/institution/FormPerson.tsx
  ClientApp/src/components/institution/FormWish.tsx
  ClientApp/src/components/institution/RegistrationForm.tsx
  ClientApp/src/components/institution/RegistrationFormTypes.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/components/institution/mockDatabase.tsx
Labels: Frontend

#832 Fix error
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Backend

#833 fixedDesignNavAndPicturesBliGiver
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarBusiness.tsx
  ClientApp/src/pages/register-as-giver/index.tsx
  ClientApp/src/styling/img/BliGiverStep1.png
  ClientApp/src/styling/img/BliGiverStep2.png
  ClientApp/src/styling/img/BliGiverStep3.png
  ClientApp/src/styling/img/BliGiverStep4.png
Labels: Frontend

#841 fixed design on FAQ component
  ClientApp/src/components/landing-page/Questions.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/index.tsx
Labels: Frontend

#839 Admin paneled finished
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewStatistics.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
Labels: Frontend

#845 Contact cards finished
  ClientApp/src/components/landing-page/Contact.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/index.tsx
  ClientApp/src/styling/img/person.png
Labels: Frontend

#849 Final changes
  ClientApp/src/components/landing-page/Contact.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/index.tsx
Labels: Frontend

#848 layout changes
  ClientApp/src/components/superadmin/Municipality/AddMunicipalityForm.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityContainer.tsx
Labels: Frontend

#850 Delete method
  ClientApp/src/components/superadmin/Municipality/MunicipalityContainer.tsx
  GiEnJul/Controllers/MunicipalityController.cs
Labels: Backend, Frontend

#847 designFixLanding Page
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/landing-page/How.tsx
  ClientApp/src/components/landing-page/StartJul.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/components/landing-page/What.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarBusiness.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
  ClientApp/src/pages/landing-page/index.tsx
  ClientApp/src/pages/municipality/index.tsx
  ClientApp/src/styling/img/bigLandingPagePicture.png
Labels: Frontend

#852 Institution form
  ClientApp/src/components/institution/FormPerson.tsx
  ClientApp/src/components/institution/FormWish.tsx
  ClientApp/src/components/institution/RegistrationForm.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/components/institution/mockDatabase.tsx
Labels: Frontend

#858 Institution form validation
  ClientApp/src/components/institution/FormPerson.tsx
  ClientApp/src/components/institution/FormWish.tsx
  ClientApp/src/components/institution/RegistrationForm.tsx
  ClientApp/src/components/institution/RegistrationFormTypes.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/components/institution/SuggestionPopover.tsx
  GiEnJul/Dtos/PostPersonDto.cs
  GiEnJul/Dtos/PutPersonDto.cs
  GiEnJul/Dtos/RecipientDataTableDto.cs
  GiEnJul/Entities/Person.cs
  GiEnJul/Models/Person.cs
Labels: Backend, Frontend

#859 Contact to municipality
  ClientApp/src/pages/landing-page/index.tsx
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Controllers/EventController.cs
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/Dtos/GetContactsDto.cs
  GiEnJul/Dtos/PostEventDto.cs
  GiEnJul/Dtos/PostMunicipalityDto.cs
  GiEnJul/Entities/Event.cs
  GiEnJul/Entities/Municipality.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Event.cs
  GiEnJul/Models/Municipality.cs
  GiEnJul/Repositories/EventRepository.cs
  GiEnJul/Repositories/MunicipalityRepository.cs
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily.html
  GiEnJul/Utilities/EmailTemplates/Files/Registered.html
  GiEnJul/Utilities/EmailTemplates/Files/WaitingList.html
Labels: Backend, Frontend

#860 Updated /Manage => Legg til kommuner & eventer
  ClientApp/src/components/landing-page/Municipalities/Municipalities.tsx
  ClientApp/src/components/landing-page/Municipalities/MunicipalityInformation.tsx
  ClientApp/src/components/landing-page/Municipalities/Styles.tsx
  ClientApp/src/components/superadmin/Faq/FaqContainer.tsx
  ClientApp/src/components/superadmin/Faq/FaqInformation.tsx
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityContainer.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityInformation.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityTableElements.tsx
  ClientApp/src/components/superadmin/MunicipalityInformation/MunicipalityInformation.tsx
  ClientApp/src/components/superadmin/MunicipalityInformation/MunicipalityInformationContainer.tsx
  ClientApp/src/components/superadmin/Styles.tsx
  ClientApp/src/pages/municipality/index.tsx
Labels: Frontend

#866 Repair single wish strings
  ClientApp/src/components/admin/connection-suggester/RecipientTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/RecipientDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/SuggestionDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/SuggestionDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientTable.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/components/shared/Types.tsx
  ClientApp/src/pages/administrator/index.tsx
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Models/Person.cs
Labels: Backend, Frontend

#868 Contact policy remove & styling
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/landing-page/StartJul.tsx
  ClientApp/src/components/register-as-giver/Confirmation.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
  GiEnJul/Controllers/MunicipalityController.cs
Labels: Backend, Frontend

#865 prevent zooming on mobile when entering a textfield
  ClientApp/public/index.html
Labels: bug

#869 Institution overview fixes and removal of unused Admin Overview files
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/GiverSearch.tsx
  ClientApp/src/components/admin/dashboard-all/GiverTable.tsx
  ClientApp/src/components/admin/dashboard-all/NEW/ScrollerComponent.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewMacro.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewStatistics.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientSearch.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientTable.tsx
  ClientApp/src/components/admin/dashboard-all/Statistics.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataTable.tsx
  ClientApp/src/components/institution/FormWish.tsx
  ClientApp/src/components/institution/RegistrationOverview.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/hooks/useUser.tsx
  ClientApp/src/pages/administrator/index.tsx
  ClientApp/src/pages/institution/index.tsx
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Repositories/MunicipalityRepository.cs
Labels: Frontend

#872 email template bugs
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Utilities/EmailTemplates/Files/EmailCssStyles.json
Labels: Backend

#875 Visual text on "legg til kommuner og eventer"
  ClientApp/src/components/superadmin/Events/EventsContainer.tsx
  ClientApp/src/components/superadmin/MuniEventUserManaging/AdminMunicipalityUserEvent.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityTableElements.tsx
Labels: Frontend

#878 Usercms
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  ClientApp/src/components/superadmin/Users/AddUser.tsx
  ClientApp/src/components/superadmin/Users/UserForm.tsx
  GiEnJul/Clients/Auth0ManagementClient.cs
  GiEnJul/Controllers/UserController.cs
Labels: Backend, Frontend

#879 Overview Fixes
  ClientApp/src/common/functions/GetFamilySize.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataTable.tsx
  ClientApp/src/pages/administrator/index.tsx
Labels: Frontend

#884 Fixed visual styling on gmail/outlook like clients
  GiEnJul/GiEnJul.csproj
  GiEnJul/Utilities/EmailTemplates/EmailTemplateBuilder.cs
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily.html
  GiEnJul/Utilities/EmailTemplates/Files/EmailCssStyles.json
  GiEnJul/Utilities/EmailTemplates/Files/Notification.html
  GiEnJul/Utilities/EmailTemplates/Files/Registered.html
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
  GiEnJul/Utilities/EmailTemplates/Files/WaitingList.html
  GiEnJul/Utilities/EmailTemplates/Files/family.png
Labels: Backend, Design

#885 Feedback and minor Admin changes
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataCard.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/pages/DenyConnection.tsx
  ClientApp/src/pages/VerifyConnection.tsx
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Repositories/ConnectionRepository.cs
  GiEnJul/Repositories/MunicipalityRepository.cs
  GiEnJul/Utilities/EmailTemplates/EmailTemplateName.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.Designer.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.resx
  GiEnJul/Utilities/EmailTemplates/Files/ConnectionDenied.html
Labels: Frontend

#890 Moved table
  ClientApp/src/components/superadmin/ManageDashboard.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/AddMunicipalityForm.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityTableElements.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipalityContainer.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityInformation/MunicipalityInformation.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityInformation/MunicipalityInformationContainer.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/MunicipalityInformation/MunicipalityInformationContainer.tsx
  GiEnJul/Controllers/MunicipalityController.cs
Labels: Frontend

#889 Send email from admin and institution
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/components/shared/SendEmailContent.tsx
Labels: Frontend

#893 Visual design for test
  ClientApp/src/components/shared/ConfirmationBox.tsx
  ClientApp/src/components/shared/InformationBox.tsx
  ClientApp/src/components/shared/SendEmailContent.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  ClientApp/src/components/superadmin/Faq/FaqContainer.tsx
  ClientApp/src/components/superadmin/Faq/FaqInformation.tsx
  ClientApp/src/components/superadmin/InfoPages/HowToStartGiEnJul.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/AddMunicipalityForm.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityTableElements.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityInformation/MunicipalityInformation.tsx
  ClientApp/src/components/superadmin/Styles.tsx
Labels: Frontend

#895 emailFix
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/components/shared/SendEmailContent.tsx
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/EmailController.cs
  GiEnJul/Utilities/EmailTemplates/Files/Notification.html
Labels: Backend

#898 all user functionality
  ClientApp/src/components/superadmin/Users/AddUser.tsx
  ClientApp/src/components/superadmin/Users/UserForm.tsx
  GiEnJul/Clients/Auth0ManagementClient.cs
  GiEnJul/Controllers/UserController.cs
  GiEnJul/Infrastructure/Settings.cs
  GiEnJul/appsettings.json
Labels: Backend, Frontend

#899 button
  ClientApp/src/components/superadmin/Events/NewEventBox.tsx
Labels: Frontend
