Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2022-08, with the labels that each got.

#902 add registrationDate to givers in filldb.py
  scripts/filldb/filldb.py
Labels: extra

#907 removed email Image and "hei" from notification
  GiEnJul/Utilities/EmailTemplates/EmailTemplateBuilder.cs
  GiEnJul/Utilities/EmailTemplates/Files/Notification.html
Labels: bug

#908 icon navbar bli giver confirmation page
  ClientApp/src/components/register-as-giver/Confirmation.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/pages/register-as-giver/index.tsx
Labels: bug, Frontend

#910 disabled vis informasjon when editing kommune
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityTableElements.tsx
Labels: Frontend

#913 Manage users inputvalidation
  ClientApp/src/common/constants/Roles.tsx
  ClientApp/src/components/superadmin/Events/EventValidation.tsx
  ClientApp/src/components/superadmin/Users/AddUser.tsx
  ClientApp/src/components/superadmin/Users/UserForm.tsx
  GiEnJul/Clients/Auth0ManagementClient.cs
  GiEnJul/Controllers/UserController.cs
  GiEnJul/appsettings.json
Labels: Backend, Frontend

#915 fix design mobile on sub landing pages
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/landing-page/StartJul.tsx
  ClientApp/src/components/shared/navbar/NavBarMobile.tsx
Labels: Frontend

#918 Months disable overview institution
  ClientApp/src/components/shared/EditFamilyDialog.tsx
Labels: Frontend

#920 Replace keynotfound exception
  GiEnJul/Repositories/EventRepository.cs
Labels: Backend

#916 mobile nav bar bli-giver
  ClientApp/src/components/shared/navbar/NavBarMobile.tsx
Labels: Frontend

#921 Test fix
  GiEnJul.Test/ControllerTests/GiverControllerTest.cs
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/Repositories/MunicipalityRepository.cs
Labels: Backend

#923 Fixed issue with Admin Panel misbehavior
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataTable.tsx
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/ConnectionController.cs
  GiEnJul/Dtos/DeleteConnectionDto.cs
  GiEnJul/Helpers/ConnectionHelper.cs
Labels: bug

#926 Email age fix
  GiEnJul/Models/Person.cs
Labels: bug

#933 connection Error Page
  ClientApp/src/pages/VerifyConnection.tsx
Labels: Frontend

#937 Deny connection text change and some styling
  ClientApp/src/pages/DenyConnection.tsx
Labels: Frontend

#931 User metadata
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/CmsController.cs
  GiEnJul/Controllers/ManageController.cs
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/Repositories/MunicipalityRepository.cs
Labels: Backend

#939 Included status in overview
  ClientApp/package.json
  ClientApp/src/components/institution/RegistrationOverview.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/index.tsx
Labels: Frontend

#943 Auto dc mailtemplate
  GiEnJul/GiEnJul.csproj
  GiEnJul/Helpers/EmailDictionaryHelper.cs
  GiEnJul/Repositories/GenericRepository.cs
  GiEnJul/Startup.cs
  GiEnJul/Utilities/EmailTemplates/EmailTemplateName.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.Designer.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.resx
  GiEnJul/Utilities/EmailTemplates/Files/AutomaticDisconnect.html
  GiEnJul/Utilities/EmailTemplates/Files/ConnectionReminder.html
  GiEnJul/Utilities/ScheduledJobs/CleanupConnectionsJob.cs
Labels: Backend

#942 Form validation now functions properly and has updated visuals
  ClientApp/src/common/constants/Genders.tsx
  ClientApp/src/common/functions/GetGender.tsx
  ClientApp/src/components/institution/FormPerson.tsx
  ClientApp/src/components/institution/FormWish.tsx
  ClientApp/src/components/institution/RegistrationForm.tsx
  ClientApp/src/components/institution/Styles.tsx
  ClientApp/src/index.tsx
Labels: bug, Frontend

#946 changes
  ClientApp/src/common/functions/IsMobile.tsx
  ClientApp/src/components/register-as-giver/Pager.tsx
  ClientApp/src/components/register-as-giver/Steppers.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/components/register-as-giver/Summary.tsx
  ClientApp/src/pages/register-as-giver/index.tsx
Labels: Frontend

#950 add funky waves to landing page 🏄‍♂️ 🤙
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/components/shared/WavedSeparator.tsx
  ClientApp/src/pages/landing-page/index.tsx
Labels: extra

#952 Visual and functional updates to admin overview
  ClientApp/src/components/admin/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewMacroRemake.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewStatistics.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataTable.tsx
  ClientApp/src/components/admin/dashboard-all/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataTable.tsx
  ClientApp/src/components/admin/dashboard-completed/DeliveryExcelDownload.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/index.tsx
Labels: Frontend

#951 Verify connection pagev4
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/pages/VerifyConnection.tsx
Labels: Frontend

#956 bli-giver mobile next / prev button bug
  ClientApp/src/components/register-as-giver/ContactInfo.tsx
  ClientApp/src/components/register-as-giver/Pager.tsx
  ClientApp/src/components/register-as-giver/Styles.tsx
  ClientApp/src/components/register-as-giver/Summary.tsx
Labels: Frontend

#957 bug resolved
  ClientApp/src/components/institution/RegistrationForm.tsx
Labels: bug

#962 design and superadmin right
  ClientApp/src/components/landing-page/Contact.tsx
  ClientApp/src/components/landing-page/Questions.tsx
  ClientApp/src/components/landing-page/Styles.tsx
  ClientApp/src/components/superadmin/Business/BusinessInformation.tsx
  ClientApp/src/components/superadmin/InfoPages/HowToStartGiEnJul.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityManageTable.tsx
  GiEnJul/Utilities/Authorization.cs
Labels: Frontend

#960 Contact image
  ClientApp/src/components/landing-page/Contact.tsx
Labels: Frontend

#961 Images municipality
  ClientApp/src/components/landing-page/Municipalities/Municipalities.tsx
  ClientApp/src/components/landing-page/Municipalities/MunicipalityInformation.tsx
  ClientApp/src/components/landing-page/Municipalities/Styles.tsx
  ClientApp/src/pages/municipality/index.tsx
  GiEnJul/Controllers/MunicipalityController.cs
  GiEnJul/Dtos/GetMunicipalityDto.cs
  GiEnJul/Entities/Municipality.cs
  GiEnJul/Infrastructure/AutoMapperProfile.cs
  GiEnJul/Models/Municipality.cs
Labels: Backend, Frontend

#963 stop logging errors from TryGet()
  GiEnJul/Repositories/GenericRepository.cs
Labels: Backend

#966 fixes minor issues
  ClientApp/src/components/register-as-giver/ContactInfo.tsx
  ClientApp/src/components/superadmin/Faq/FaqInformation.tsx
Labels: Frontend

#967 Icon updates
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewConnection.tsx
  ClientApp/src/components/admin/dashboard-all/OverviewStatistics.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/SuggestionDataCard.tsx
  ClientApp/src/components/institution/FormPerson.tsx
  ClientApp/src/components/institution/RegistrationOverview.tsx
  ClientApp/src/components/institution/Styles.tsx
Labels: Frontend

#970 disconnected givers are pushed to the bottom
  GiEnJul/Controllers/AdminController.cs
Labels: Backend

#971 Fix edit family dialog
  ClientApp/src/components/admin/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/GiverDataCard.tsx
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
Labels: Frontend

#973 Snowfall
  ClientApp/package.json
  ClientApp/src/pages/landing-page/index.tsx
Labels: Design

#974 fix sorting
  GiEnJul/Controllers/AdminController.cs
Labels: Backend

#972 fixed the new DTO
  GiEnJul/Dtos/GetMunicipalityDto.cs
Labels: Backend

#977 small positioning fixes
  ClientApp/src/components/landing-page/Municipalities/Styles.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
Labels: Frontend

#978 bug fix
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityTableElements.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipalityContainer.tsx
  ClientApp/src/components/superadmin/Municipality/MunicipalityInformation/MunicipalityInformation.tsx
Labels: Frontend

#983 visual fixes for new release
  ClientApp/src/components/admin/dashboard-all/RecipientDataCard.tsx
  ClientApp/src/components/landing-page/Contact.tsx
  ClientApp/src/components/landing-page/How.tsx
  ClientApp/src/components/superadmin/Events/EventInformation.tsx
  ClientApp/src/components/superadmin/Events/EventRow.tsx
  ClientApp/src/components/superadmin/Events/EventsContainer.tsx
  ClientApp/src/components/superadmin/Events/EventsTable.tsx
  ClientApp/src/components/superadmin/Faq/FaqContainer.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipality/MunicipalityManageTable.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipalityContainer.tsx
Labels: Frontend

#985 deny/verify
  ClientApp/src/pages/DenyConnection.tsx
  ClientApp/src/pages/VerifyConnection.tsx
Labels: Frontend

#986 Footer
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/landing-page/Contact.tsx
  ClientApp/src/components/landing-page/Municipalities/Municipalities.tsx
  ClientApp/src/components/landing-page/Questions.tsx
  ClientApp/src/components/landing-page/StartJul.tsx
  ClientApp/src/components/shared/Footer.tsx
  ClientApp/src/components/shared/Styles.tsx
  ClientApp/src/components/superadmin/Municipality/ManageMunicipalityContainer.tsx
  ClientApp/src/pages/landing-page/index.tsx
  ClientApp/src/pages/municipality/index.tsx
Labels: Frontend
