Repository capgemini-stavanger/gi-en-jul, pull requests merged in 2022-06, with the labels that each got.

#603 .net6 and new table package
  .github/workflows/CI_backend.yml
  .github/workflows/DEV_CD_backend.yml
  .github/workflows/PROD_CD_backend.yml
  .gitignore
  GiEnJul.Test/ControllerTests/AdminControllerTest.cs
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul.Test/GiEnJul.Test.csproj
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/GiverController.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Controllers/VerifyConnectionController.cs
  GiEnJul/Entities/EntityBase.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Helpers/TableQueryFilterHelper.cs
  GiEnJul/Infrastructure/AutofacConfiguration.cs
  GiEnJul/Repositories/AutoIncrementRepository.cs
  GiEnJul/Repositories/ConnectionRepository.cs
  GiEnJul/Repositories/EventRepository.cs
  GiEnJul/Repositories/GenericRepository.cs
  GiEnJul/Repositories/GiverRepository.cs
  GiEnJul/Repositories/PersonRepository.cs
  GiEnJul/Repositories/RecipientRepository.cs
  GiEnJul/Utilities/RecaptchaVerifier.cs
Labels: Technical, .NET

#625 In case of multiple reactUri's use the last one #605
  GiEnJul/Controllers/AdminController.cs
Labels: Backend

#632 validating refernceId backend
  GiEnJul.Test/ControllerTests/RecipientControllerTest.cs
  GiEnJul/Controllers/RecipientController.cs
  GiEnJul/Repositories/RecipientRepository.cs
Labels: Feature, Backend

#626 Split confirm email
  GiEnJul/Controllers/AdminController.cs
  GiEnJul/Controllers/VerifyConnectionController.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Utilities/EmailTemplates/EmailTemplateName.cs
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily.html
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
Labels: Backend

#635 Check reference id front end
  ClientApp/src/components/institution/InstitutionForm.tsx
Labels: Frontend

#639 Created business page with routing
  ClientApp/src/App.tsx
  ClientApp/src/components/landing-page/Business.tsx
  ClientApp/src/components/shared/navbar/NavBarPublic.tsx
Labels: Frontend

#638 New email controller
  GiEnJul/Auth/Authconfig.cs
  GiEnJul/Controllers/EmailController.cs
  GiEnJul/Dtos/PostEmailDto.cs
Labels: Feature, Backend

#645 Wrap email templates
  GiEnJul.Test/UtilTests/EmailTemplateBuilderTests.cs
  GiEnJul/Controllers/EmailController.cs
  GiEnJul/GiEnJul.csproj
  GiEnJul/Utilities/EmailTemplates/EmailTemplateBuilder.cs
  GiEnJul/Utilities/EmailTemplates/EmailTemplateName.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.Designer.cs
  GiEnJul/Utilities/EmailTemplates/EmailTitles.resx
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily - styled.html
  GiEnJul/Utilities/EmailTemplates/Files/AssignedFamily.html
  GiEnJul/Utilities/EmailTemplates/Files/Notification.html
  GiEnJul/Utilities/EmailTemplates/Files/Registered.html
  GiEnJul/Utilities/EmailTemplates/Files/TemplateStyle.css
  GiEnJul/Utilities/EmailTemplates/Files/VerifyConnection.html
  GiEnJul/Utilities/EmailTemplates/Files/WaitingList.html
Labels: Backend

#653 Send single email frontend
  ClientApp/package.json
  ClientApp/src/components/admin/Styles.tsx
  ClientApp/src/components/admin/dashboard-all/GiverTable.tsx
  ClientApp/src/components/shared/SendEmailContent.tsx
Labels: Frontend

#661 npm packages and svg file
  ClientApp/package-lock.json
  ClientApp/package.json
  ClientApp/src/styling/img/logo_green.svg
Labels: dependencies, Frontend

#679 Remake edit family
  ClientApp/src/components/admin/dashboard-all/RecipientTable.tsx
  ClientApp/src/components/institution/FamilyDialog.tsx
  ClientApp/src/components/shared/EditFamilyDialog.tsx
  ClientApp/src/components/shared/Types.tsx
Labels: Frontend
